[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Luke Storry <luke@storry.uk>"]
edition = "2018"
repository = "https://github.com/lukestorry/advent-of-code-2020/"
description = "My Rusty solutions to aoc 2020"

[dependencies]
regex = "1.4.2"
lazy_static = "1.3.0"
